package pmp.tianxundai.com.notepaddemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import pmp.tianxundai.com.notepaddemo.bean.StudentsBean;

import pmp.tianxundai.com.notepaddemo.greendao.StudentsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentsBeanDaoConfig;

    private final StudentsBeanDao studentsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentsBeanDaoConfig = daoConfigMap.get(StudentsBeanDao.class).clone();
        studentsBeanDaoConfig.initIdentityScope(type);

        studentsBeanDao = new StudentsBeanDao(studentsBeanDaoConfig, this);

        registerDao(StudentsBean.class, studentsBeanDao);
    }
    
    public void clear() {
        studentsBeanDaoConfig.clearIdentityScope();
    }

    public StudentsBeanDao getStudentsBeanDao() {
        return studentsBeanDao;
    }

}
